replicaCount: 1
image:
  useImagePullSecrets: false
  pullPolicy: Always
service:
  internalPort: 8080
  externalPort: 8080
ingress:
  enabled: true
  basedomain: aks-prod-fa483a1d.hcp.brazilsouth.azmk8s.io # replace with your own from the portal
